spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb?reWriteBatchedInserts=true
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

batch:
  injector:
    input-file: classpath:contracts_input.txt
    chunk-size: 100
    output-file: src/main/resources/invalid-contracts.txt

logging:
  level:
    org.springframework.batch: INFO
    com.bnpparibas.dsibddf.ap23992.modeldevente.batch.injector: DEBUG
