spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchdb?reWriteBatchedInserts=true
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

contract:
  import:
    input-file: classpath:visa-premier.txt
    invalid-file: src/main/resources/invalid-contracts.txt
    charset: UTF-8

logging:
  level:
    org.springframework.batch: INFO
    com.example.jobaggregator: DEBUG
