-- Test-only schema: creates tables for H2 in PostgreSQL compatibility mode.
-- Uses GENERATED BY DEFAULT AS IDENTITY instead of BIGSERIAL/AUTO_INCREMENT.

CREATE TABLE IF NOT EXISTS contracts (
    id                      UUID          PRIMARY KEY,
    devise                  VARCHAR(3)    NOT NULL,
    state                   VARCHAR(2)    NOT NULL,
    motif                   VARCHAR(50),
    ou_distribution         VARCHAR(255),
    ou_management           VARCHAR(50)   NOT NULL,
    address_id              VARCHAR(50),
    business_relationship   VARCHAR(100)  NOT NULL,
    effective_date          VARCHAR(35),
    periode_facturation     VARCHAR(20),
    dates_facturation       VARCHAR(100),
    x_b3_trace_id           VARCHAR(16)   NOT NULL,
    x_b3_span_id            VARCHAR(16)   NOT NULL,
    user_id                 VARCHAR(16)   NOT NULL,
    channel                 VARCHAR(3)    NOT NULL,
    media                   VARCHAR(3)    NOT NULL,
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_offers (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    offer_id            VARCHAR(50)   NOT NULL,
    personalized_label  VARCHAR(255),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_marketed_objects (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id             UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    om_id                   VARCHAR(50)   NOT NULL,
    business_relationship   VARCHAR(100)  NOT NULL,
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_articles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    marketed_object_id  BIGINT        NOT NULL REFERENCES contract_marketed_objects (id) ON DELETE CASCADE,
    sequential_index    INT           NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_accounts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    article_id          BIGINT        REFERENCES contract_articles (id) ON DELETE CASCADE,
    level               VARCHAR(10)   NOT NULL,
    sub_type            VARCHAR(10)   NOT NULL,
    bic                 VARCHAR(11)   NOT NULL,
    iban                VARCHAR(34)   NOT NULL,
    rib                 VARCHAR(50),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_roles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    marketed_object_id  BIGINT        REFERENCES contract_marketed_objects (id) ON DELETE CASCADE,
    article_id          BIGINT        REFERENCES contract_articles (id) ON DELETE CASCADE,
    level               VARCHAR(10)   NOT NULL,
    role                VARCHAR(10)   NOT NULL,
    brand               VARCHAR(10)   NOT NULL,
    scope               VARCHAR(10)   NOT NULL,
    holder_id           VARCHAR(50)   NOT NULL,
    ikpi                VARCHAR(50)   NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_external_ids (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    marketed_object_id  BIGINT        REFERENCES contract_marketed_objects (id) ON DELETE CASCADE,
    article_id          BIGINT        REFERENCES contract_articles (id) ON DELETE CASCADE,
    level               VARCHAR(10)   NOT NULL,
    external_id         VARCHAR(50)   NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_ikac (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    article_id          BIGINT        NOT NULL REFERENCES contract_articles (id) ON DELETE CASCADE,
    ikac_value          VARCHAR(100)  NOT NULL,
    provider            VARCHAR(50)   NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_conditions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    article_id          BIGINT        NOT NULL REFERENCES contract_articles (id) ON DELETE CASCADE,
    condition_id        VARCHAR(50)   NOT NULL,
    condition_value     VARCHAR(100)  NOT NULL,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_tarifs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id             UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    marketed_object_id      BIGINT        REFERENCES contract_marketed_objects (id) ON DELETE CASCADE,
    article_id              BIGINT        REFERENCES contract_articles (id) ON DELETE CASCADE,
    level                   VARCHAR(10)   NOT NULL,
    id_opra_tarif           VARCHAR(50),
    type_frais              VARCHAR(10),
    date_creation_tarif     VARCHAR(35),
    date_effet_tarif        VARCHAR(35),
    devise_tarif            VARCHAR(3),
    indic_tarif_paliers     VARCHAR(1),
    format_tarif            VARCHAR(10),
    periodicite_facturation VARCHAR(10),
    type_taxation           VARCHAR(10),
    type_taux_tarif         VARCHAR(10),
    taux_tarif              VARCHAR(25),
    montant_base            VARCHAR(25),
    ratio_tarif             VARCHAR(25),
    montant_unite           VARCHAR(25),
    type_unite              VARCHAR(10),
    indic_limite_haute      VARCHAR(1),
    limite_haute_montant    VARCHAR(25),
    indic_limite_basse      VARCHAR(1),
    limite_basse_montant    VARCHAR(25),
    created_at              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contract_advantages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id         UUID          NOT NULL REFERENCES contracts (id) ON DELETE CASCADE,
    marketed_object_id  BIGINT        REFERENCES contract_marketed_objects (id) ON DELETE CASCADE,
    article_id          BIGINT        REFERENCES contract_articles (id) ON DELETE CASCADE,
    level               VARCHAR(10)   NOT NULL,
    id_opra_avantage    VARCHAR(50),
    date_debut          VARCHAR(35)   NOT NULL,
    date_fin            VARCHAR(35),
    code_avantage       VARCHAR(5)    NOT NULL,
    valeur_avantage     VARCHAR(25),
    devise_avantage     VARCHAR(3),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
